name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r AILogDemo/requirements.txt

    - name: Run unit tests (Placeholder)
      run: echo "No unit tests defined yet. Add your tests here."

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push producer image
      uses: docker/build-push-action@v5
      with:
        context: ./AILogDemo
        file: ./AILogDemo/Dockerfile.producer
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ailogdemo-producer:latest

    - name: Build and push consumer image
      uses: docker/build-push-action@v5
      with:
        context: ./AILogDemo
        file: ./AILogDemo/Dockerfile.consumer
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ailogdemo-consumer:latest
